import subprocess
import os
from pathlib import Path
from .db import get_target_files # We'll need to impl this or similar to get file paths

class NebulaLauncher:
    def __init__(self, pi_executable_path=r"C:\Program Files\PixInsight\bin\PixInsight.exe"):
        self.pi_path = pi_executable_path

    def generate_script(self, target_name, file_groups):
        """
        Generates a PJSR script to load files into WBPP or just open them.
        For now, this is a placeholder that prints to the PI console.
        """
        script_content = f"""
/* 
   NebulaPilot Integration Script for Target: {target_name}
   Generated by NebulaPilot
*/

console.show();
console.writeln("NebulaPilot: Starting integration setup for {target_name}...");

// In the future, this would populate WBPP. 
// For now, we verify we can launch and identify the target.
console.writeln("Source Files:");
"""
        # Add file logging (mock for now)
        for f_type, files in file_groups.items():
             script_content += f'console.writeln("  {f_type}: {len(files)} files");\n'

        script_content += """
console.writeln("NebulaPilot: Script finished. Please open WBPP manually.");
"""
        
        script_path = Path(f"temp_script_{target_name}.js").absolute()
        with open(script_path, "w") as f:
            f.write(script_content)
        
        return script_path

    def run_target(self, target_name, source_dir):
        """
        Generates script and launches PixInsight.
        """
        # Retrieve real file list from DB
        file_groups = get_target_files(target_name)
        
        script_path = self.generate_script(target_name, file_groups)
        
        # Standard launch
        cmd = [self.pi_path, "-r=" + str(script_path)]
        
        print(f"Launching PixInsight: {cmd}")
        # subprocess.Popen(cmd) # Uncomment to actually run if PI is installed
        
        return True
